import { useState, useRef } from 'react';

const reportData = {
  period: 'May 12 – May 18, 2026',
  generated: new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' }),
  summary: {
    totalMentions: '39.6K',
    positiveRate: '61%',
    negativeRate: '23%',
    neutralRate: '16%',
    topPlatform: 'Twitter / X',
    analysisAccuracy: '94.2%',
  },
  topTrends: [
    { topic: '#Business', mentions: '3.3K', growth: '-5%' },
    { topic: '#Politics', mentions: '2.9K', growth: '+3%' },
    { topic: '#General', mentions: '1.1K', growth: '+8%' },
    { topic: '#Technology', mentions: '840', growth: '+12%' },
    { topic: '#Media', mentions: '620', growth: '+4%' },
  ],
  topInfluencers: [
    { user: '@pjohnson', score: 96.0, community: 'Politics' },
    { user: '@rachel65', score: 92.4, community: 'Business' },
    { user: '@charlesschneider', score: 88.7, community: 'Politics' },
    { user: '@fcooper', score: 84.1, community: 'General' },
  ],
  alerts: [
    { severity: 'High', title: 'Elevated Negative Sentiment Spike in Business', time: '15 min ago' },
    { severity: 'Medium', title: 'Surging Discussion Volume: Business', time: '35 min ago' },
    { severity: 'Info', title: 'High Resonance Topic: Politics', time: '1 hour ago' },
  ],
  recommendations: [
    'Prioritize community response review and prepare proactive talking points for stakeholders.',
    'Amplify positive community narratives in #Business and engage high-resonance discussions.',
    'Monitor emerging key contributors with rapid engagement trajectories.',
    'Address negative sentiment clusters around critical discussion points promptly.',
    'Maintain sustained engagement in #Politics community forums.',
  ],
};

export default function Reports() {
  const [generated, setGenerated] = useState(false);
  const [generating, setGenerating] = useState(false);
  const reportRef = useRef(null);

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => {
      setGenerating(false);
      setGenerated(true);
    }, 1800);
  };

  const handleDownload = () => {
    // Build a text-based report and download as .txt for demo
    const lines = [
      '════════════════════════════════════════════════════════',
      '           SOCIALSENSE AI — ANALYSIS REPORT            ',
      '════════════════════════════════════════════════════════',
      '',
      `Period:    ${reportData.period}`,
      `Generated: ${reportData.generated}`,
      `Platform:  All Platforms`,
      '',
      '── EXECUTIVE SUMMARY ────────────────────────────────',
      `Total Mentions:      ${reportData.summary.totalMentions}`,
      `Positive Sentiment:  ${reportData.summary.positiveRate}`,
      `Negative Sentiment:  ${reportData.summary.negativeRate}`,
      `Neutral Sentiment:   ${reportData.summary.neutralRate}`,
      `Top Platform:        ${reportData.summary.topPlatform}`,
      `AI Accuracy:         ${reportData.summary.analysisAccuracy}`,
      '',
      '── TOP TRENDING TOPICS ──────────────────────────────',
      ...reportData.topTrends.map((t, i) => `${i + 1}. ${t.topic.padEnd(20)} ${t.mentions.padEnd(8)} ${t.growth}`),
      '',
      '── TOP INFLUENCERS ──────────────────────────────────',
      ...reportData.topInfluencers.map((inf, i) => `${i + 1}. ${inf.user.padEnd(18)} Score: ${inf.score}  Community: ${inf.community}`),
      '',
      '── ACTIVE ALERTS ────────────────────────────────────',
      ...reportData.alerts.map((a, i) => `${i + 1}. [${a.severity}] ${a.title} — ${a.time}`),
      '',
      '── AI RECOMMENDATIONS ───────────────────────────────',
      ...reportData.recommendations.map((r, i) => `${i + 1}. ${r}`),
      '',
      '════════════════════════════════════════════════════════',
      '    Generated by SocialSense AI — Confidential         ',
      '   "Turning Social Data Into Actionable Intelligence"  ',
      '════════════════════════════════════════════════════════',
    ];

    const content = lines.join('\n');
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SocialSense_Report_${reportData.period.replace(/[^a-zA-Z0-9]/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <div className="page-header">
        <div className="page-header-left">
          <h1>Reports</h1>
          <p>Generate and export comprehensive intelligence reports</p>
        </div>
        <div className="header-controls">
          <button className="btn btn-primary" onClick={handleGenerate} disabled={generating}>
            {generating ? (
              <span style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <span style={{ width: 14, height: 14, border: '2px solid rgba(255,255,255,0.3)', borderTopColor: '#fff', borderRadius: '50%', animation: 'spin 0.8s linear infinite', display: 'inline-block' }} />
                Generating...
              </span>
            ) : 'Generate Report'}
          </button>
          {generated && (
            <button className="btn btn-secondary" onClick={handleDownload}>
              Download Report
            </button>
          )}
        </div>
      </div>

      <div className="page-body">
        {!generated ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: 400 }}>
            <div style={{ fontSize: 56, marginBottom: 20, fontWeight: 800, color: 'var(--brand-primary)' }}>SS</div>
            <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 8 }}>Generate Your Analysis Report</h2>
            <p style={{ color: 'var(--text-muted)', fontSize: 14, marginBottom: 28, textAlign: 'center', maxWidth: 400 }}>
              Click "Generate Report" to create a comprehensive summary of all social intelligence insights.
            </p>
            <button className="btn btn-primary" style={{ padding: '12px 28px', fontSize: 15 }} onClick={handleGenerate} disabled={generating}>
              {generating ? 'Generating...' : '⚡ Generate Report'}
            </button>
            {generating && (
              <div style={{ marginTop: 20, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
                <div style={{ width: 240, height: 4, background: 'var(--surface-3)', borderRadius: 'var(--radius-full)', overflow: 'hidden' }}>
                  <div style={{ height: '100%', background: 'linear-gradient(90deg, var(--brand-primary), var(--brand-accent))', borderRadius: 'var(--radius-full)', animation: 'generateBar 1.8s ease forwards', width: '100%' }} />
                </div>
                <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>Compiling insights...</span>
              </div>
            )}
          </div>
        ) : (
          <div ref={reportRef} className="report-preview fade-in-up" id="report-content">
            {/* Report Header */}
            <div className="report-header">
              <div className="report-logo">
                <div style={{ width: 44, height: 44, background: 'linear-gradient(135deg, #6366f1, #22d3ee)', borderRadius: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 14, fontWeight: 800, color: '#fff' }}>
                  SS
                </div>
                <div>
                  <div className="report-title">SocialSense AI</div>
                  <div className="report-subtitle">Social Intelligence Analysis Report</div>
                </div>
              </div>
              <div style={{ textAlign: 'right' }}>
                <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-primary)' }}>{reportData.period}</div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>Generated: {reportData.generated}</div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>All Platforms</div>
              </div>
            </div>

            {/* Executive Summary */}
            <div className="report-section">
              <div className="report-section-title">Executive Summary</div>
              <div className="report-grid">
                {Object.entries(reportData.summary).map(([k, v]) => (
                  <div key={k} className="report-stat">
                    <div className="report-stat-val">{v}</div>
                    <div className="report-stat-label">{k.replace(/([A-Z])/g, ' $1').trim()}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Top Trends */}
            <div className="report-section">
              <div className="report-section-title">Top Trending Topics</div>
              <table className="data-table" style={{ fontSize: 13 }}>
                <thead>
                  <tr>
                    <th>#</th><th>Topic</th><th>Mentions</th><th>Growth</th>
                  </tr>
                </thead>
                <tbody>
                  {reportData.topTrends.map((t, i) => (
                    <tr key={i}>
                      <td style={{ fontWeight: 700, color: 'var(--text-muted)' }}>{i + 1}</td>
                      <td style={{ fontWeight: 700, color: 'var(--brand-primary)' }}>{t.topic}</td>
                      <td>{t.mentions}</td>
                      <td style={{ color: t.growth.startsWith('+') ? 'var(--color-positive)' : 'var(--color-negative)', fontWeight: 700 }}>{t.growth}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Top Influencers */}
            <div className="report-section">
              <div className="report-section-title">Top Influencers</div>
              <table className="data-table">
                <thead>
                  <tr><th>#</th><th>User</th><th>Influence Score</th><th>Community</th></tr>
                </thead>
                <tbody>
                  {reportData.topInfluencers.map((inf, i) => (
                    <tr key={i}>
                      <td style={{ fontWeight: 700, color: 'var(--text-muted)' }}>{i + 1}</td>
                      <td style={{ fontWeight: 700 }}>{inf.user}</td>
                      <td style={{ fontWeight: 700, color: 'var(--brand-primary)' }}>{inf.score}</td>
                      <td><span className="badge badge-info">{inf.community}</span></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Alerts */}
            <div className="report-section">
              <div className="report-section-title">Important Alerts</div>
              {reportData.alerts.map((a, i) => (
                <div key={i} style={{
                  display: 'flex', alignItems: 'center', gap: 12,
                  padding: '10px 14px', marginBottom: 8,
                  background: 'var(--surface-2)', borderRadius: 8,
                  borderLeft: `3px solid ${a.severity === 'High' ? '#ef4444' : a.severity === 'Medium' ? '#f59e0b' : '#3b82f6'}`
                }}>
                  <span className={`badge badge-${a.severity === 'High' ? 'negative' : a.severity === 'Medium' ? 'neutral' : 'info'}`}>
                    {a.severity}
                  </span>
                  <span style={{ fontSize: 13, flex: 1 }}>{a.title}</span>
                  <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{a.time}</span>
                </div>
              ))}
            </div>

            {/* Recommendations */}
            <div className="report-section">
              <div className="report-section-title">AI Recommendations</div>
              {reportData.recommendations.map((rec, i) => (
                <div key={i} className="report-rec">
                  <div className="report-rec-num">{i + 1}</div>
                  {rec}
                </div>
              ))}
            </div>

            <div style={{ textAlign: 'center', padding: '20px 0 0', borderTop: '1px solid var(--border)', color: 'var(--text-muted)', fontSize: 12 }}>
              <strong>SocialSense AI</strong> — "Turning Social Data Into Actionable Intelligence" · Confidential
            </div>
          </div>
        )}
      </div>
    </>
  );
}
